AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false
  
Metrics/LineLength:
  Enabled: false
  Max: 120

MethodLength:
  Enabled: false

StringLiterals:
  Enabled: false
