development:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_dev
  pool: 5
  host: localhost
  username: ofn
  password: f00d

test:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  host: localhost
  username: ofn
  password: f00d

#not used with heroku
production:
  adapter: postgresql
  encoding: unicode
  database: dfsiqg8q0flump
  pool: 5
  username: peqzuasugqodcc
  password: 3562904301276b72a22d26d15ccbef49a16fd0a94a965ab1118d2405d020638a
  host: ec2-54-243-187-133.compute-1.amazonaws.com

staging:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_prod
  pool: 5
  username: ofn
  password: f00d
